eureka:
  instance:
    prefer-ip-address: true
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  
  okta:
    oauth2:
      issuer: https://integrator-6808070.okta.com/oauth2/default
      audience: api://default
